# NumPy

## designed for fast numerical computing

### python lists - heterogeneous, slow
### numpy arrays (ndarray) - homogeneous, fast because it is optimised with C language 

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


#### how fast are numpy arrays?

In [7]:
import time

size = 100_000_000

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python List : {end - start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2 # notice that we didn't use the loop at all, we just performed the operation as a whole on the array (VECTORIZATION)
end = time.time()
print(f"Numpy Array : {end - start} seconds")

Python List : 13.873908281326294 seconds
Numpy Array : 1.028554916381836 seconds


#### let's compare memory aswell?

In [8]:
import sys

print(f"Python List : {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy Array : {np_arr.nbytes} bytes")

Python List : 80000005600000000 bytes
Numpy Array : 800000000 bytes


#### why python lists occupy more memory?
- numpy arrays store elements in contiguous memory location
- whereas the list stores each element in different location, with different location comes the meta-data associated with it (address and other stuff)

## creating numpy array - using lists

In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, 6, "Hello"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' '6' 'Hello'] <class 'numpy.ndarray'> (7,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
