# NumPy

## designed for fast numerical computing

### python lists - heterogeneous, slow
### numpy arrays (ndarray) - homogeneous, fast because it is optimised with C language 

In [2]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


#### how fast are numpy arrays?

In [5]:
import time

size = 10_000_000

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python List : {end - start} seconds")

np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2 # notice that we didn't use the loop at all, we just performed the operation as a whole on the array (VECTORIZATION)
end = time.time()
print(f"Numpy Array : {end - start} seconds")

Python List : 5.289608955383301 seconds
Numpy Array : 0.19747471809387207 seconds


#### let's compare memory aswell?

In [ ]:
import sys

print(f"Python List : {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy Array : {np_arr.nbytes} bytes")

Python List : 80000005600000000 bytes
Numpy Array : 800000000 bytes


#### why python lists occupy more memory?
- numpy arrays store elements in contiguous memory location
- whereas the list stores each element in different location, with different location comes the meta-data associated with it (address and other stuff)

## creating numpy array - using lists

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, 6, "Hello"])
print(arr2, type(arr2), arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' '6' 'Hello'] <class 'numpy.ndarray'> (7,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


## creating numpy array - from scratch

In [ ]:
arr = np.zeros((2, 3), dtype="int64") # prefil by 0
print(arr, arr.shape)

arr2 = np.ones((3, 4)) # prefill by 1
print(arr2, arr2.shape)

arr3 = np.full((4, 3), 69) # prefill by a specific number
print(arr3, arr3.shape)

arr4 = np.eye(3) # identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 11, 2) # in a range of numbers
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 5) # evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[69 69 69]
 [69 69 69]
 [69 69 69]
 [69 69 69]] (4, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.    25.75  50.5   75.25 100.  ] (5,)


### some functions associated with numpy

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr.shape) # return dimensions
print(arr.size) # returns no. of elements in a numpy array
print(arr.dtype) # return datatype
print(arr.ndim) # returns the no. of dimensions of an array

float_arr = arr.astype(np.float64) # change the datatype of an array from existing array
print(float_arr, float_arr.dtype) # if you're creating from scratch, the above cell is example

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


### operations on numpy arrays

- reshaping of an array

In [13]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr, reshaped_arr.shape)

flattened = reshaped_arr.flatten()
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


- indexing (iD & 2D)

In [17]:
arr = np.array([1,2,3,4,5])
print(arr[0], arr[3], arr[4])

arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2[0][2], arr2[1][1], arr2[2][0])

1 4 5
3 5 7


- fancy indexing

In [ ]:
arr = np.array([1,2,3,4,5])

ind = [1, 0, 2] # store all the indexes you want

print(arr[ind]) # as numpy arrays are vectorized you can do this operations as a whole, not possible with lists

[2 1 3]


- boolean indexing

In [19]:
arr = np.array([1,2,3,4,5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


- slicing

In [20]:
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[:4])
print(arr[1:])
print(arr[:])
print(arr[::2]) # skips a number, alternate element

[2 3 4]
[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[1 3 5]


### even though slicing is same as in lists, but there's a huge differnce
- lists create a copy of  the sliced array -> hence they are slow
- numpy arrays create a view i.e., any changes to the sliced array -> change in original array

In [ ]:
list = [1,2,3,4,5]
sliced_list = list[1:3]
print(sliced_list)
sliced_list[0] = 200 # replace the value
print(sliced_list)
print(list) # notice the original array has not changed

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [22]:
arr = np.array([1,2,3,4,5])
sliced_arr = arr[1:3]
print(sliced_arr)
sliced_arr[0] = 200
print(sliced_arr)
print(arr)

[2 3]
[200   3]
[  1 200   3   4   5]


### numpy - common datatypes

In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, arr.dtype)

arr = np.array([1, 2, 3.4, 4, 5])
print(arr, arr.dtype)

arr = np.array([1, 2, 3.4, 4, 5, "shaik"])
print(arr, arr.dtype)

arr = np.array([True, False, False])
print(arr, arr.dtype)

arr = np.array([3 + 5j])
arr2 = np.array([6 + 9j])
print(arr - arr2, arr.dtype)

[1 2 3 4 5] int64
[1.  2.  3.4 4.  5. ] float64
['1' '2' '3.4' '4' '5' 'shaik'] <U32
[ True False False] bool
[-3.-4.j] complex128


### axes in multi-dimensional array
- 1D -> 1 axis (axis 0)
- 2D -> 2 axes (axis 0 - rows -> vertical operation
                | axis 1 - column -> horizontal operation)
- 3D -> 3 axes (axis 0 - depth/layers | 
                axis 1 - rows | 
                axis 2 - colums)

In [ ]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print()

sum = np.sum(arr2D)
print(sum)
print()

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)
print()

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)
print()

# slicing with 2D arrays
print(arr2D[0:2, 1:2]) # [rows, colums]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

45

[12 15 18]

[ 6 15 24]

[[2]
 [5]]


In [24]:
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) # 2 x 3 x 2
print()
print(arr3D, arr3D.shape)
print()

# indexing in 3D array
print(arr3D[0, 1, 1], arr3D[1, 1, 0]) # [layer, row, col]
print()

# slicing
print(arr3D[:, 0, :]) # first rows from both layers
print(arr3D[:, 1, 1])
print()

arr3D[:, 0, :] = 99 # we can manipulate also
print(arr3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)

4 9

[[1 2]
 [7 8]]
[ 4 10]

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


### vectorization

In [25]:
arr = np.array([1,2,3,4,5])

print(arr ** 2)

arr2 = np.array([6,7,8,9,10])

print(arr + arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


### broadcasting
- making differently-shaped arrays work together by automatically expanding/repeating dimensions where allowed.
- Broadcasting compares dimensions from right to left. Every pair must either MATCH or have a 1.

In [30]:
arr = np.array([[1,2,3], [4,5,6]]) # (2, 3)
arr2 = np.array([1,2,3]) # (3, )
print(arr + arr2) # (2, 3) -> ( ,3) = valid

arr = np.array([[1,2,3], [4,5,6]]) # (2, 3)
arr2 = np.array([[1], [2]]) # (2, 1)
print(arr + arr2) # (2, 3) -> (2, 1) = valid

arr = np.array([[1,2,3], [4,5,6]]) # (2, 3)
arr2 = np.array([[1, 2]]) # (2, )
#print(arr + arr2) # (2, 3) -> ( ,2) = not valid

[[2 4 6]
 [5 7 9]]
[[2 3 4]
 [6 7 8]]


### vector normalization
- one of the uses of broadcasting is vector normalization
- normalizing a vector means trabsforming it's values, so that they fit into a specific scale or range

### standard normalization (z-score normalization)
- (arr - mean) / standard_deviation
- standard_deviation = sqrt(((val[i] - mean)^2) / 2)

In [6]:
arr = np.array([[1, 2], [3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

print(mean)
print(std_dev)
print(np.sqrt(5/4))
print()

print((arr - mean)/std_dev)

2.5
1.118033988749895
1.118033988749895

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


### other functions associated with numpy
- aggregation functions

In [11]:
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) # returns the index of min value
print(np.argmax(arr)) # returns the index of max value
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr)) # sigma
print(np.var(arr)) # sigma^2

15
120
1
5
0
4
3.0
3.0
1.4142135623730951
2.0


- power functions

In [12]:
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


- logarithmic functions

In [15]:
arr = np.array([1,2,3,4,5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


- rounding functions

In [21]:
print(np.round(3.14))
print(np.round(3.84))

print(np.ceil(3.14)) # round up
print(np.floor(3.14)) # round down

print(np.trunc(3.14)) # truncates the decimal places

3.0
4.0
4.0
3.0
3.0


- other functions

In [22]:
arr = np.array([-1,1,-2,5,-3,7,7,5])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[-3 -2 -1  1  5  7]
[-3 -2 -1  1  5  5  7  7]
[1 1 2 5 3 7 7 5]
